# Generated by Django 3.2.5 on 2021-08-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=64)),
                ('definition', models.TextField(max_length=1024)),
                ('lesson', models.BigIntegerField(default=0)),
                ('tags', models.CharField(blank=True, choices=[('HW', 'Hardware'), ('PG', 'Programming'), ('C', 'C')], default=None, max_length=2)),
                ('link', models.CharField(max_length=96)),
            ],
        ),
    ]
