# Generated by Django 3.2.5 on 2021-08-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.filepage'),
        ),
        migrations.AlterField(
            model_name='term',
            name='link',
            field=models.CharField(default=models.CharField(max_length=64), max_length=96),
        ),
    ]
