# Generated by Django 3.2.5 on 2021-08-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20210809_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='link',
            field=models.CharField(max_length=96),
        ),
    ]
