# Generated by Django 3.1.5 on 2021-06-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_term_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='link',
            field=models.CharField(max_length=96),
        ),
    ]
