# Generated by Django 3.1.5 on 2021-02-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestpage',
            name='chapterpath',
            field=models.CharField(default='h1', max_length=16),
        ),
        migrations.AlterField(
            model_name='latestpage',
            name='path',
            field=models.CharField(default='1', max_length=16),
        ),
    ]
