# Generated by Django 3.2.5 on 2021-08-08 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldprogress',
            name='filepage',
        ),
        migrations.AddField(
            model_name='oldprogress',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.course'),
        ),
    ]
