# Generated by Django 3.2.5 on 2021-08-08 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('home', '0002_auto_20210808_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldprogress',
            name='course',
        ),
        migrations.AddField(
            model_name='oldprogress',
            name='filepage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='files.filepage'),
        ),
    ]
