# Generated by Django 3.1.5 on 2021-02-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210226_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestPage',
        ),
    ]
