# Generated by Django 3.1.5 on 2021-03-01 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courselist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('chapterpath', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='chapterpath',
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.courselist'),
        ),
    ]
