# Generated by Django 3.1.5 on 2021-03-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210301_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='starterpath',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
