# Generated by Django 3.2.5 on 2022-12-22 11:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterpath', models.CharField(max_length=16)),
                ('path', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('file', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ['chapterpath', 'path'],
            },
        ),
        migrations.CreateModel(
            name='LatestVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.lesson')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
