# Generated by Django 3.2.5 on 2021-08-08 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterpath', models.CharField(blank=True, default='h1', max_length=16, null=True)),
                ('path', models.CharField(default='1', max_length=16)),
                ('title', models.CharField(default='title', max_length=32)),
                ('file', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LatestPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='files.filepage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
