# Generated by Django 3.2.5 on 2021-08-09 11:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepage',
            name='file',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
