# Generated by Django 4.0.2 on 2022-12-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_lesson_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='markdown',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.TextField(),
        ),
    ]
