# Generated by Django 3.1.5 on 2021-02-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
            ],
        ),
    ]
