# Generated by Django 3.1.5 on 2021-02-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_filepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepage',
            name='path',
            field=models.CharField(default='1', max_length=16),
        ),
    ]
