# Generated by Django 3.2.5 on 2021-11-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210809_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filepage',
            options={'ordering': ['chapterpath', 'path']},
        ),
    ]
