# Generated by Django 3.1.5 on 2021-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_filepage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepage',
            name='chapterpath',
            field=models.CharField(default='h1', max_length=32),
        ),
    ]
