# Generated by Django 3.1.5 on 2021-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_filepage_chapterpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepage',
            name='title',
            field=models.CharField(default='title', max_length=32),
        ),
    ]
