# Generated by Django 3.1.5 on 2021-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='definition',
            field=models.TextField(max_length=1024),
        ),
    ]
