# Generated by Django 3.1.5 on 2021-04-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_auto_20210406_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Term',
        ),
    ]
